### ISSUE TITLE
Add "last activity date" to the PR attributes

### ISSUE THREAD

**Issue by caarmen** [CedricCabessa/gm_pr#24]
Not sure if this exists in the github apis.  If it does, it would be cool to see the date of the last activity (comment, commit, ... ?) on the PR.

**Comment by CedricCabessa** [comment]
We already use the "updated_at" attribute to know if a PR is considered "OLD".
It's in PrFetcher.py, should be easy to display

**Comment by caarmen** [comment]
You may assign this to me.

**Comment by calvarez-ov** [comment]
This may be closed now.

**Comment by CedricCabessa** [comment]
Thx ;-)
