### ISSUE TITLE
Move to genymobile organization

### ISSUE THREAD

**Issue by CedricCabessa** [CedricCabessa/gm_pr#30]
This (awesome) project should be a genyproject.

To achieve this, we need:
 * Make sure the code is clean and readable (or at least not ugly)
 * Make sure we respect basic python/django best practice (PEP8, ...)
 * Have a README
 * Have a screenshot of the app
 * Put the apache License in every file and in the project dir
 * Maybe have a link to genymobile or at least to the github repo in the footer of the app

**Comment by caarmen** [comment]
You probably don't want to have a screenshot of the PR list of the private genymotion repos.  I was trying to find some popular repos to have a screenshot of.  Here's one example.  They have no milestones and labels, barely any validation indicators, and most of the PRs are old :)

Maybe we can find a better screenshot :)
<img width="1161" alt="squareprlist" src="https://cloud.githubusercontent.com/assets/1731388/9018795/43f9a872-37e3-11e5-8582-812af9d02e0c.png">

**Comment by caarmen** [comment]
A more colorful one:
<img width="1156" alt="googleprlist" src="https://cloud.githubusercontent.com/assets/1731388/9019163/cb4d2b6a-37e7-11e5-9b11-a3dbe39e3f8a.png">

**Comment by CedricCabessa** [comment]
Very nice!!! thanks.
I'll use this one
